apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: game-library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nomadstormbreaker/backend:2
        ports:
        - containerPort: 5000
        env:
        - name: DB_URL
          value: mongodb://root:password@mongodb-service:27017/gamestore?authSource=admin

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: game-library
spec:
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
