apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: game-library
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-immediate
  hostPath:
    path: /mnt/data  # Use an appropriate path for your environment