apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: game-library
spec:
  storageClassName: gp2-immediate
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
